setup postgre tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -56,5 +56,54 @@ jobs:
           sqlcmd -Q "CREATE SCHEMA receiver AUTHORIZATION db_owner" -d "nservicebus"
           sqlcmd -Q "CREATE SCHEMA sender AUTHORIZATION db_owner" -d "nservicebus"
           sqlcmd -Q "CREATE SCHEMA db@ AUTHORIZATION db_owner" -d "nservicebus"
+      - name: Azure login
+        uses: azure/login@v2.1.0
+        with:
+          creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}    
+      - name: Setup PostgreSql 15.x
+        id: setup-postgresql
+        run: |
+          echo "Getting the Azure region in which this workflow is running..."
+          $hostInfo = curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | ConvertFrom-Json
+          $region = $hostInfo.compute.location
+          echo "Actions agent running in Azure region: $region"
+
+          $name = "postgres-$(Get-Random)"
+          $packageTag = "Package=SqlPersistence"
+          $runnerOsTag = "RunnerOS=$($Env:RUNNER_OS)"
+          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
+
+          $password = [guid]::NewGuid().ToString("n")
+          echo "::add-mask::$password"
+
+          echo "Creating PostgreSQL container $name (This can take a while)"
+          $details = az container create --image postgres:15 --name $name --location $region --dns-name-label $name --resource-group GitHubActions-RG --cpu 2 --memory 8 --ports 5432 --ip-address public --environment-variables POSTGRES_PASSWORD="$password" | ConvertFrom-Json
+          echo "name=$name" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf-8 -Append
+
+          echo "Tagging container"
+          $ignore = az tag create --resource-id $details.id --tags $packageTag $runnerOsTag $dateTag
+
+          $fqdn = $details.ipAddress.fqdn
+          echo "::add-mask::$fqdn"
+
+          $connectionString = "User ID=postgres;Password=$password;Host=$fqdn;Port=5432;Database=postgres;"
+          echo "PostgreSqlConnectionString=$connectionString" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
+
+          $env:PGPASSWORD = $password
+
+          # psql not in PATH on Windows
+          if ($Env:RUNNER_OS -eq 'Windows') {
+            $Env:PATH = $Env:PATH + ';' + $Env:PGBIN
+          }
+
+          for ($i = 0; $i -lt 24; $i++) { ## 2 minute timeout
+            echo "Checking for PostgreSQL connectivity $($i+1)/30..."
+            $ignore = psql --host $fqdn --username=postgres --list
+            if ($?) {
+              echo "Connection successful"
+              break;
+            }
+            sleep 5
+          }
       - name: Run tests
         uses: Particular/run-tests-action@v1.7.0
